name: Multi Jobs Workflow 
on: [ push ]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Build Step
     run: echo "Running step of build job."
 test:
  runs-on: ubuntu-latest
  needs: [build]
  steps:
   - name: Test Step
     run: echo "Running step of the test job."
 deploy:
  runs-on: ubuntu-latest
  needs: [test]
  steps:
   - name: Deploy Step
     run: echo "Running step of deploy job."
